default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t web-app:latest .
  tags:
    - daniil

test:
  stage: test
  script:
    - docker run web-app:latest python -m unittest discover
  allow_failure: true
  tags:
    - daniil
    
deploy:
  stage: deploy
  script:
    - docker run -d -p 5000:5000 web-app:latest  
  tags:
    - daniil